avinetworks/avi-helm-charts

README.md
ako-beta/values.yaml
docs/values.md

Added the info related to `deleteConfig` values.yaml param on different pages
Replaced `shardPrefix `with `clusterName `as shardPrefix is a deprecated field

deleteConfig doc changes

---

docs/troubleshooting.md

Addition of log collection details for AKO
- The public location of the script.
- About the script
- How to configure PVC
- How to run
- Output

Log collection

---

docs/objects.md

Changes related to multi-port service documentation.

Doc update for multi-port service support

---

docs/AKO/crds/hostrule.md
docs/AKO/crds/overview.md

This  describes the new CRDs being introduced with AKO release 1.1.1
The HTTPRule CRD will be updated in a subsequent PR.

HostRule CRD related documentation

---

docs/AKO/crds/httprule.md
docs/AKO/crds/overview.md

This PR has doc changes related to the HTTPRule CRD.

Updates related to httprule CRD

---

docs/AKO/README.md

- Initial readme changes for node port and openshift support
- Other docs like faq, values  would be added in next PRs

Update AKO README for service type node port and Openshift

---

docs/AKO/crds/overview.md

Updated the CRD header for the page.

Updated the CRD header

---

docs/AMKO/README.md

Also, updated the parameters section.

AMKO app and chart version updates

---

docs/AMKO/README.md

Add --devel in the docs. Change the controllerIP parameter in the
helm install command.

Fix the helm search command for AMKO

---

docs/AKO/README.md

This PR lists down changes for the AKO 1.1.1 release and optionally specifies an upgrade path as well.

Changes for 1.1.1

---

charts/incubator/ako/values.yaml

special char <200b> was added in values yaml, yaml was showing as invalid

Fixed special char typos in values yaml

---

docs/AKO/faq.md
docs/AKO/objects.md
docs/AKO/values.md

- route spec for multi port service

openshift update for ako 1.2.1 release

---

docs/AKO/objects.md
docs/AKO/values.md

@sudswasavi @monotosh-avi @hemantavi @parimanur @shubhamavi Please review.

Document Namespace Sync feature

---

docs/AKO/README.md
docs/AKO/faq.md
docs/AKO/openshift/openshift.md

- Also moved the section for openshift to a new page

Documentation for AKO statefulset status update on all object deletion

---

docs/AKO/README.md
docs/AKO/install/helm.md
docs/AKO/install/operator.md

- Created an install directory and move helm and operator within it.
- Adjusted some fonts.
- Got rid of some redundant sections.

Re-shuffling the docs

---

docs/AKO/crds/hostrule.md
docs/AKO/objects.md

`datascripts` referred to as plural
newline addition

formatting fixes

---

docs/AKO/roles/ako-essential.json

Adding ako-essential role which can be assigned to AKO user in admin tenant.

---

docs/AKO/AKO_Operator.md

Takes care of https://github.com/avinetworks/avi-helm-charts/issues/108.

Add finalizer step to AKO Operator

---

docs/AKO/crds/avinfrasetting.md
docs/AKO/crds/hostrule.md
docs/AKO/crds/httprule.md
docs/AKO/gateway-api/gateway-api.md
docs/AKO/ingress/ingress.md
docs/AKO/values.md

ApplicationPersistenceProfile support via HttpRule doc

AviInfraSetting CRD usage documentation and field descriptions

---

CHANGELOG.md

Updates to change log for AKO 1.4.3
